## Introduction to Pandas

In [3]:
# importing packages
import pandas as pd

In [8]:
# Create a dataframe using a dictionary
x = {
    'name':['Priyanshi', 'Samruddhi', 'Sameer', 'Vaibhav', 'Atharv'],
    '9':[1, 1, 1, 1, 2]
}
dfX = pd.DataFrame(x)
print(dfX)

        name  9
0  Priyanshi  1
1  Samruddhi  1
2     Sameer  1
3    Vaibhav  1
4     Atharv  2

In [13]:
# Reading a CSV file
df = pd.read_csv('../datasets/GenZ_DatingApp_Data.csv')
df

,User_ID,Age,Gender,Location,Education,Occupation,Primary_App,Secondary_Apps,Usage_Frequency,Daily_Usage_Time,Reason_for_Using,Satisfaction,Challenges,Desired_Features,Preferred_Communication,Partner_Priorities
0,1,20,Non-binary,Bangalore,Undergraduate,Freelancer,Hinge,Hinge,Monthly,1 hour,Finding a Partner,4,Safety Concerns,Audio Calls,Video Calls,Values > Personality > Appearance
1,2,24,Female,Delhi,Undergraduate,Part-time Job,Hinge,OkCupid,Weekly,30 minutes,Casual Dating,5,Time-Wasting,Video Calls,Text,Values > Personality > Appearance
2,3,24,Non-binary,Kolkata,Undergraduate,Intern,NaN,NaN,Weekly,2 hours,Casual Dating,4,Safety Concerns,Detailed Profiles,Text,Values > Personality > Appearance
3,4,22,Non-binary,Delhi,Graduate,Full-time Job,NaN,OkCupid,Daily,30 minutes,Casual Fun,3,NaN,AI Recommendations,Voice Notes,Personality > Interests > Values
4,5,18,Male,Delhi,Graduate,Intern,OkCupid,OkCupid,Weekly,2 hours,Casual Fun,4,Safety Concerns,Video Calls,Text,Appearance > Interests > Personality
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,23,Female,Mumbai,Undergraduate,Intern,Tinder,Hinge,Weekly,1.5 hours,Casual Dating,2,NaN,Audio Calls,Voice Notes,Personality > Interests > Values
496,497,23,Male,Mumbai,Postgraduate,Intern,OkCupid,Tinder,Daily,2 hours,Casual Fun,1,Time-Wasting,Video Calls,Video Calls,Values > Personality > Appearance
497,498,22,Male,Hyderabad,Graduate,Freelancer,NaN,Hinge,Monthly,2 hours,Casual Fun,2,Lack of Genuine Matches,Video Calls,Voice Notes,Appearance > Interests > Personality
498,499,21,Female,Kolkata,Graduate,Student,Tinder,Hinge,Daily,1.5 hours,Casual Dating,3,Lack of Genuine Matches,Detailed Profiles,Text,Appearance > Interests > Personality
499,500,22,Male,Mumbai,Graduate,Part-time Job,NaN,Hinge,Weekly,1.5 hours,Casual Fun,2,Time-Wasting,AI Recommendations,Video Calls,Appearance > Interests > Personality

In [21]:
# Accessing data row-wise
print(df.loc[0])
print(df.loc[0:1])

User_ID                                                    1
Age                                                       20
Gender                                            Non-binary
Location                                           Bangalore
Education                                      Undergraduate
Occupation                                        Freelancer
Primary_App                                            Hinge
Secondary_Apps                                         Hinge
Usage_Frequency                                      Monthly
Daily_Usage_Time                                      1 hour
Reason_for_Using                           Finding a Partner
Satisfaction                                               4
Challenges                                   Safety Concerns
Desired_Features                                 Audio Calls
Preferred_Communication                          Video Calls
Partner_Priorities         Values > Personality > Appearance
Name: 0, dtype: object
   User_ID  Age      Gender   Location      Education     Occupation  \
0        1   20  Non-binary  Bangalore  Undergraduate     Freelancer
1        2   24      Female      Delhi  Undergraduate  Part-time Job

  Primary_App Secondary_Apps Usage_Frequency Daily_Usage_Time  \
0       Hinge          Hinge         Monthly           1 hour
1       Hinge        OkCupid          Weekly       30 minutes

    Reason_for_Using  Satisfaction       Challenges Desired_Features  \
0  Finding a Partner             4  Safety Concerns      Audio Calls
1      Casual Dating             5     Time-Wasting      Video Calls

  Preferred_Communication                 Partner_Priorities
0             Video Calls  Values > Personality > Appearance
1                    Text  Values > Personality > Appearance

In [20]:
# Accessing data column-wise
print(df['Occupation'])

0         Freelancer
1      Part-time Job
2             Intern
3      Full-time Job
4             Intern
           ...
495           Intern
496           Intern
497       Freelancer
498          Student
499    Part-time Job
Name: Occupation, Length: 500, dtype: object

## Analyzing data using Pandas

In [25]:
print(df.head(10))

   User_ID  Age      Gender   Location      Education     Occupation  \
0        1   20  Non-binary  Bangalore  Undergraduate     Freelancer
1        2   24      Female      Delhi  Undergraduate  Part-time Job
2        3   24  Non-binary    Kolkata  Undergraduate         Intern
3        4   22  Non-binary      Delhi       Graduate  Full-time Job
4        5   18        Male      Delhi       Graduate         Intern
5        6   23      Female     Mumbai  Undergraduate        Student
6        7   22  Non-binary    Chennai   Postgraduate  Part-time Job
7        8   21      Female       Pune   Postgraduate     Freelancer
8        9   20        Male       Pune   Postgraduate  Part-time Job
9       10   20  Non-binary    Chennai  Undergraduate         Intern

  Primary_App Secondary_Apps Usage_Frequency Daily_Usage_Time  \
0       Hinge          Hinge         Monthly           1 hour
1       Hinge        OkCupid          Weekly       30 minutes
2         NaN            NaN          Weekly          2 hours
3         NaN        OkCupid           Daily       30 minutes
4     OkCupid        OkCupid          Weekly          2 hours
5     OkCupid            NaN           Daily        1.5 hours
6      Tinder         Tinder         Monthly       30 minutes
7       Hinge         Tinder          Weekly        1.5 hours
8       Hinge        OkCupid           Daily          2 hours
9     OkCupid         Bumble          Weekly          3 hours

    Reason_for_Using  Satisfaction               Challenges  \
0  Finding a Partner             4          Safety Concerns
1      Casual Dating             5             Time-Wasting
2      Casual Dating             4          Safety Concerns
3         Casual Fun             3                      NaN
4         Casual Fun             4          Safety Concerns
5      Casual Dating             2                      NaN
6  Finding a Partner             4             Time-Wasting
7  Finding a Partner             2          Safety Concerns
8  Finding a Partner             1  Lack of Genuine Matches
9  Finding a Partner             1          Safety Concerns

          Desired_Features Preferred_Communication  \
0              Audio Calls             Video Calls
1              Video Calls                    Text
2        Detailed Profiles                    Text
3       AI Recommendations             Voice Notes
4              Video Calls                    Text
5              Audio Calls             Video Calls
6              Audio Calls                    Text
7              Audio Calls             Video Calls
8              Audio Calls                    Text
9  Location-Based Matching             Video Calls

                     Partner_Priorities
0     Values > Personality > Appearance
1     Values > Personality > Appearance
2     Values > Personality > Appearance
3      Personality > Interests > Values
4  Appearance > Interests > Personality
5     Values > Personality > Appearance
6      Personality > Interests > Values
7     Values > Personality > Appearance
8     Values > Personality > Appearance
9     Values > Personality > Appearance

In [27]:
print(df.tail())

     User_ID  Age  Gender   Location      Education     Occupation  \
495      496   23  Female     Mumbai  Undergraduate         Intern
496      497   23    Male     Mumbai   Postgraduate         Intern
497      498   22    Male  Hyderabad       Graduate     Freelancer
498      499   21  Female    Kolkata       Graduate        Student
499      500   22    Male     Mumbai       Graduate  Part-time Job

    Primary_App Secondary_Apps Usage_Frequency Daily_Usage_Time  \
495      Tinder          Hinge          Weekly        1.5 hours
496     OkCupid         Tinder           Daily          2 hours
497         NaN          Hinge         Monthly          2 hours
498      Tinder          Hinge           Daily        1.5 hours
499         NaN          Hinge          Weekly        1.5 hours

    Reason_for_Using  Satisfaction               Challenges  \
495    Casual Dating             2                      NaN
496       Casual Fun             1             Time-Wasting
497       Casual Fun             2  Lack of Genuine Matches
498    Casual Dating             3  Lack of Genuine Matches
499       Casual Fun             2             Time-Wasting

       Desired_Features Preferred_Communication  \
495         Audio Calls             Voice Notes
496         Video Calls             Video Calls
497         Video Calls             Voice Notes
498   Detailed Profiles                    Text
499  AI Recommendations             Video Calls

                       Partner_Priorities
495      Personality > Interests > Values
496     Values > Personality > Appearance
497  Appearance > Interests > Personality
498  Appearance > Interests > Personality
499  Appearance > Interests > Personality

In [28]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   User_ID                  500 non-null    int64
 1   Age                      500 non-null    int64
 2   Gender                   500 non-null    object
 3   Location                 500 non-null    object
 4   Education                500 non-null    object
 5   Occupation               500 non-null    object
 6   Primary_App              393 non-null    object
 7   Secondary_Apps           386 non-null    object
 8   Usage_Frequency          500 non-null    object
 9   Daily_Usage_Time         500 non-null    object
 10  Reason_for_Using         500 non-null    object
 11  Satisfaction             500 non-null    int64
 12  Challenges               383 non-null    object
 13  Desired_Features         500 non-null    object
 14  Preferred_Communication  500 non-null    object
 15  Partner_Priorities       500 non-null    object
dtypes: int64(3), object(13)
memory usage: 62.6+ KB
None

In [31]:
print(df.describe())

          User_ID         Age  Satisfaction
count  500.000000  500.000000    500.000000
mean   250.500000   21.582000      2.906000
std    144.481833    2.259532      1.441291
min      1.000000   18.000000      1.000000
25%    125.750000   20.000000      2.000000
50%    250.500000   22.000000      3.000000
75%    375.250000   24.000000      4.000000
max    500.000000   25.000000      5.000000

## Cleaning data using Pandas

Types of common errors in data:
1. Empty Values
2. Incorrect values
3. Duplicate values